### ISSUE TITLE
Minor syntax error causing plugin to fail parsing

### ISSUE THREAD

**Issue by toughquestions** [unixorn/fzf-zsh-plugin#100]
For the commit `502e3670b68a6633c99a95877521ea733d543446` [link](https://github.com/unixorn/fzf-zsh-plugin/commit/502e3670b68a6633c99a95877521ea733d543446) ,
getting this error:

```
/home/user/.zgenom/unixorn/fzf-zsh-plugin/___/fzf-zsh-plugin.plugin.zsh:50: parse error: condition expected: _fzf_has
```

Changing line 50 https://github.com/unixorn/fzf-zsh-plugin/blob/502e3670b68a6633c99a95877521ea733d543446/fzf-zsh-plugin.plugin.zsh#L50  by removing the brackets to 
```zsh
if ! _fzf_has fzf ; then
```

seems to fix the issue.

**Comment by unixorn** [comment]
Fixed by https://github.com/unixorn/fzf-zsh-plugin/pull/99
