### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by ThreshMain** [unixorn/fzf-zsh-plugin#28]
fzf-zsh-plugin.plugin.zsh is incorrect and oh-my-zsh will not find it
use fzf-zsh.plugin.zsh instead

**Comment by unixorn** [comment]
Are you adding it as `fzf-zsh` or as `fzf-zsh-plugin` in your `.zshrc`?

**Comment by alextes** [comment]
the latter. changing to the former works.

shall we update the readme? (: https://github.com/unixorn/fzf-zsh-plugin#zgenom

**Comment by ThreshMain** [comment]
> Are you adding it as `fzf-zsh` or as `fzf-zsh-plugin` in your `.zshrc`?
`fzf-zsh`
as is said in the readme

**Comment by alextes** [comment]
I think I maybe left out too much detail still @unixorn. The readme says:

>Zgenom
>add zgenom load unixorn/fzf-zsh-plugin to your .zshrc with your other load commands.

So I did, but that didn't work. Updating to `fzf-zsh` does work 🙌 .

Thanks for the cool plugin!

**Comment by alextes** [comment]
disregard what I said, don't know what is going on but adding `zgenom load unixorn/fzf-zsh-plugin` simply breaks somehow.
![Screenshot 2021-08-20 at 13 39 53](https://user-images.githubusercontent.com/2011351/130227817-8f1858a4-4c81-41f5-903b-a3c3c2753e56.png)

**Comment by unixorn** [comment]
That should be fixed by https://github.com/unixorn/fzf-zsh-plugin/pull/31
