### ISSUE TITLE
Commited .zwc by mistake

### ISSUE THREAD

**Issue by patrickli** [unixorn/fzf-zsh-plugin#38]
Hi author, it seems I committed the complied version of `fzf-zsh-plugin.plugin.zsh` by mistake in one of my previous PRs. Can you delete `fzf-zsh-plugin.plugin.zsh.zwc` please?

Maybe also add `*.zwc` to `.gitignore` as well.

Sorry about the trouble.

**Comment by unixorn** [comment]
No problem, I didn't notice it either.
