### ISSUE TITLE
Can't find a fzf configuration file at .fzf.zsh, creating a default one

### ISSUE THREAD

**Issue by woropajj** [unixorn/fzf-zsh-plugin#52]
Steps:
1. Installed `fzf` using `sudo apt install fzf`.
2. Cloned `zgenom` and `zsh-quickstart-kit` repos to `~`.
3. `cd zsh-quickstart-kit` and symlinked using `stow`.
4. Opened new terminal window and got a message during installation:
`Can't find a fzf configuration file at .fzf.zsh, creating a default one`

Now each time I open a new terminal I get:
```
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

/home/kuba/.fzf.zsh:source:13: no such file or directory: /home/kuba/.fzf/shell/key-bindings.zsh
```

What am I doing wrong?

**Comment by woropajj** [comment]
I set the `POWERLEVEL9K_INSTANT_PROMPT` to `quiet`.

Each time I open a new terminal I still get `/home/kuba/.fzf.zsh:source:13: no such file or directory: /home/kuba/.fzf/shell/key-bindings.zsh`.

What is new: on another machine I didn't install `fzf` before installing `zsh-quickstart-kit`. `fzf` installed itself automatically and this error doesn't occur. Any tips?

**Comment by unixorn** [comment]
Hmm. It looks like the code's expecting it to be a local install and not a global one. Which would make sense, that's how I use it on my machine.

**Comment by unixorn** [comment]
I'll take another look this weekend

**Comment by unixorn** [comment]
Life happened, I'll take try to take a look at it this week sometime

**Comment by woropajj** [comment]
> Life happened, I'll take try to take a look at it this week sometime

Sure man. I appreciate what you do.

**Comment by LudoPinelli** [comment]
Same thing here, and it seems that it is indeed related to the way fzf is installed. I removed the global installation I did of it (with apt) and let the plugin reinstall it, all works fine now.
Not a problem at all for me, but I imagine it becomes one in multi-user cases.
(Very nice plugin btw, thank you!)

**Comment by unixorn** [comment]
@woropajj  / @LudoPinelli - Where is your `fzf` installed on your systems? I'd like to get the paths so I can update the install logic.

**Comment by unixorn** [comment]
Oh, and also where's the `key-bindings.zsh` installed?

**Comment by LudoPinelli** [comment]
On Ubuntu, `fzf` is installed globally in these directories:
```sh
/usr/bin/fzf
/usr/bin/fzf-tmux
`̀``
([Ubuntu packages](https://packages.ubuntu.com/jammy/amd64/fzf/filelist))

No `key-bindings.zsh`is installed by default when `fzf` is globally installed.

**Comment by gerardbosch** [comment]
Hi Joe :)
I'm finding the exact same issue. I installed `fzf` with Linux Homebrew, the path is the following:

```
❯ which fzf
/home/linuxbrew/.linuxbrew/bin/fzf
```
and the `key-bindings.zsh`:
```
/home/linuxbrew/.linuxbrew/Cellar/fzf/0.29.0/shell/key-bindings.zsh
```

Before that, I also installed it with Nix. For that case, the path should be something like:
```
~/.nix-profile/share/fzf/key-bindings.zsh
```

**Comment by gerardbosch** [comment]
You can use this workaround in the meanwhile:

```bash
bash -c '
mkdir -p $HOME/.fzf/shell
echo "Remove ~/.fzf with the link to key-bindings when https://github.com/unixorn/fzf-zsh-plugin/issues/52 is fixed" > $HOME/.fzf/README
ln -s /home/linuxbrew/.linuxbrew/opt/fzf/shell/key-bindings.zsh $HOME/.fzf/shell/key-bindings.zsh
'
```

☝ Replace the path in `ln -s` with the path of your installation `key-bindings.zsh` file, the example is for Brew.

**Comment by fjtkfm** [comment]
Hi everyone,
I had the same problem and solved it by setting the FZF_PATH environment variable like this:

```bash
export FZF_PATH=/opt/homebrew/opt/fzf
```

After doing this, the plugin was able to find the configuration files in the Homebrew fzf directory.
