### ISSUE TITLE
Antigen installation unixorn/fzf-zsh-plugin... Error! Activate logging and try again.

### ISSUE THREAD

**Issue by gerardbosch** [unixorn/fzf-zsh-plugin#54]
Hi there!

I tried to install the plugin via antigen:

```console
antigen bundle unixorn/fzf-zsh-plugin
```

and I get the following:

```console
Installing unixorn/fzf-zsh-plugin!...
Installing unixorn/fzf-zsh-plugin... Error! Activate logging and try again.
```

I don't know how to troubleshoot that, if I look at antigen `debug.log` file I see:

```console
[TRA][1645208260.1165227890] -antigen-bundle-instal failed to clone https://github.com/unixorn/fzf-zsh-plugin.git BUNDLE
```
which does not tell me much. If I try to manually clone the repo like,

```console
cd /tmp
git clone https://github.com/unixorn/fzf-zsh-plugin.git
```

the `git clone` works. So I don't know what to check.

Thanks :pray: 

P.S. Other plugins, including `unixorn/autoupdate-antigen.zshplugin`, are downloading and loading fine.

**Comment by gerardbosch** [comment]
I found out that the root cause was https://github.com/zsh-users/antigen/issues/717, so until resolved it is required to explicitly specify the default branch in the URL when this is different from `master`:

```console
antigen bundle unixorn/fzf-zsh-plugin@main
```

**Comment by unixorn** [comment]
Sure, please make a PR with an update in the readme's `antigen` install instructions. I haven't used it in years and didn't realize it would break for non-`master` default branches.
