### ISSUE TITLE
directly run the command instead of just pasting it in the buffer.

### ISSUE THREAD

**Issue by alkeryn** [unixorn/fzf-zsh-plugin#71]
hey is it possible to paste the command and run it directly instead of having to type 2 times enter ?
thanks ! :)

**Comment by unixorn** [comment]
I prefer leaving it so that the user can pull up a previous command and edit it first before running it.

I'm not opposed to adding a setting env variable to enable behavior if you want to PR it in. Maybe `FZF_HISTORY_INSTANT_RUN` or something similar.
