### ISSUE TITLE
Add color option

### ISSUE THREAD

**Issue by seebeen** [unixorn/fzf-zsh-plugin#91]
Can an option FZF_COLOR_SCHEME be added so it's easy to setup custom colors. I don't mind doing a PR if you want to merge it :)

**Comment by unixorn** [comment]
Sure, I'm always happy to get PRs on my projects.

Make it easy for users to override by only setting it if it is unset. Something like
```sh
FZF_COLOR_SCHEME=${FZF_COLOR_SCHEME:-'PUT_YOUR_VALUE_HERE'}
```

**Comment by seebeen** [comment]
Done :)
